#!/usr/bin/env bash
cd ~/uml/linux-5.4.14/

sed '/not set/d' -i $HOME/.ddd/init
sudo ddd --args ./linux root=/dev/root rootflags=/mnt/uml_root_fs rootfstype=hostfs
## if gdb hangs you need to cleanup with the following
